name: Compile LaTeX Projects

on:
  # schedule:
  #   - cron: '0 1 * * *'
  workflow_dispatch:
  push:

jobs:
  compile-projects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fix permissions for caching
        run: |
          sudo mkdir -p /usr/local/texlive/2025
          sudo chown -R $USER:$USER /usr/local/texlive/2025
          sudo chmod -R 755 /usr/local/texlive/2025

      - name: Cache downloaded file
        uses: actions/cache@v4
        id: cache-software
        with:
          path: /usr/local/texlive/2025
          key: ${{ runner.os }}-texlive2025

      - name: install texlive
        if: steps.cache-software.outputs.cache-hit != 'true'
        run: |
          cd /tmp
          curl -O https://mirrors.tuna.tsinghua.edu.cn/tex-historic-archive/systems/texlive/2025/texlive2025.iso
          sudo mkdir -p /mnt/texlive2025
          sudo mount -o loop,ro /tmp/texlive2025.iso /mnt/texlive2025
          cd /mnt/texlive2025
          sudo ./install-tl --scheme=full --no-interaction

      - name: Install fonts
        if: steps.cache-fonts.outputs.cache-hit != 'true'
        run: |
          sudo apt update
          sudo apt install -y fonts-noto-cjk fonts-arphic-gkai00mp
          fc-cache -fv

      - name: Compile LaTeX
        run: |
          export PATH=$PATH:/usr/local/texlive/2025/bin/x86_64-linux
          latexmk -xelatex -quiet -time -jobname="茆书概率论" main.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v6
        with:
          name: "output"
          path: ./*.pdf
          retention-days: 2