name: Compile LaTeX Projects

on:
  # schedule:
  #   - cron: '0 1 * * *'
  workflow_dispatch:
  push:

jobs:
  compile-projects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fix permissions for caching
        run: |
          sudo mkdir -p /usr/local/texlive/2026
          sudo chown -R $USER:$USER /usr/local/texlive/2026
          sudo chmod -R 755 /usr/local/texlive/2026

      - name: Cache downloaded file
        uses: actions/cache@v4
        id: cache-software
        with:
          path: /usr/local/texlive/2026
          key: ${{ runner.os }}-texlive2026

      - name: install texlive
        if: steps.cache-software.outputs.cache-hit != 'true'
        run: |
          cd /tmp
          curl -O https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/Images/texlive2026.iso
          sudo mkdir -p /mnt/texlive2026
          sudo mount -o loop,ro /tmp/texlive2026.iso /mnt/texlive2026
          cd /mnt/texlive2026
          sudo ./install-tl --scheme=full --no-interaction

      - name: Install fonts
        if: steps.cache-fonts.outputs.cache-hit != 'true'
        run: |
          sudo apt update
          sudo apt install -y fonts-noto-cjk fonts-arphic-gkai00mp
          fc-cache -fv

      # - name: Compile LaTeX
      #   run: |
      #     export PATH=$PATH:/usr/local/texlive/2026/bin/x86_64-linux
      #     latexmk -xelatex -quiet -time -jobname="茆书概率论" main.tex

      # - name: Upload PDF
      #   uses: actions/upload-artifact@v6
      #   with:
      #     name: "output"
      #     path: ./*.pdf
      #     retention-days: 2